'Accept' : '*/*',
'Accept-Encoding' : 'gzip, deflate',
'Accept-Language' : 'zh-CN,zh;q=0.9',
'Cache-Control' : 'no-cache',
'Connection' : 'keep-alive',
'Content-Length' : '36',
'content-type' : 'application/x-www-form-urlencoded',
'Host' : 'hb18meta.com:8084',
'Origin' : 'http://hb18meta.com',
'Pragma' : 'no-cache',
'Referer' : 'http://hb18meta.com/',
'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36',